project:
  type: book
  output-dir: docs

book:
  title: "Makroökonomik -- Wohlstand und Stabilität"
  subtitle: "Sommersemester 2026" 
  author: "Prof. Dr. Jan S. Voßwinkel"
  language:  _language.yml
  repo-url: https://github.com/janvoss/Makro.git

  chapters:
    - index.qmd
    - Einleitung.qmd
    - VGR.qmd
    - Geld.qmd
    - Inflation.qmd
    - Kurze-Frist.qmd
    - Lange-Frist.qmd
    - Makropolitik.qmd
    - Literatur.qmd
    - Uebungsfragen.qmd

bibliography: Makro.bib

format:
  html:
    theme: cosmo
    code-fold: true
    code-overflow: wrap
    

editor: source

